// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkeU_ZDDAbumTNOh4nBsK-uxAoMa0EJE',
    appId: '1:819034955091:web:4e13cefa8cd015a8dc15a6',
    messagingSenderId: '819034955091',
    projectId: 'tripextras-32f8c',
    authDomain: 'tripextras-32f8c.firebaseapp.com',
    storageBucket: 'tripextras-32f8c.firebasestorage.app',
    measurementId: 'G-QJ84VFJFZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtCHZtqLxYAdWymcMb5bd-hM4wRwwY9I',
    appId: '1:819034955091:android:4a7834c89323e6c6dc15a6',
    messagingSenderId: '819034955091',
    projectId: 'tripextras-32f8c',
    storageBucket: 'tripextras-32f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABiLUvaRhhlG820Ed5n6IfIA1oPXDuw2Y',
    appId: '1:819034955091:ios:ff90bf468a8c41a7dc15a6',
    messagingSenderId: '819034955091',
    projectId: 'tripextras-32f8c',
    storageBucket: 'tripextras-32f8c.firebasestorage.app',
    iosBundleId: 'com.example.tripextrasProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABiLUvaRhhlG820Ed5n6IfIA1oPXDuw2Y',
    appId: '1:819034955091:ios:ff90bf468a8c41a7dc15a6',
    messagingSenderId: '819034955091',
    projectId: 'tripextras-32f8c',
    storageBucket: 'tripextras-32f8c.firebasestorage.app',
    iosBundleId: 'com.example.tripextrasProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSkeU_ZDDAbumTNOh4nBsK-uxAoMa0EJE',
    appId: '1:819034955091:web:826c3b19982b55efdc15a6',
    messagingSenderId: '819034955091',
    projectId: 'tripextras-32f8c',
    authDomain: 'tripextras-32f8c.firebaseapp.com',
    storageBucket: 'tripextras-32f8c.firebasestorage.app',
    measurementId: 'G-T9LB1FBJX2',
  );
}
